@echo off
echo Compiling...
javac -cp "lib/mysql-connector-j-9.6.0.jar" -sourcepath src -d bin src/main/Main.java src/database/DBConnection.java src/model/Car.java src/model/Customer.java src/model/Rental.java src/service/CarService.java src/service/CustomerService.java src/service/RentalService.java src/ui/AppWindow.java src/ui/BasePanel.java src/ui/LoginPanel.java src/ui/DashboardPanel.java src/ui/AddCarPanel.java src/ui/ViewCarsPanel.java src/ui/ViewCustomersPanel.java src/ui/RegisterCustomerPanel.java src/ui/RentCarPanel.java src/ui/ReturnCarPanel.java
echo Running...
java -cp "bin;lib/mysql-connector-j-9.6.0.jar" main.Main
